version: 2

models:
- name: stg_bond
  columns:
  - name: effective_date
  - name: cusip
  - name: series
  - name: trade_date
  - name: issue_date
  - name: maturity_date
  - name: type
  - name: first_coupon_date
  - name: coupon_freq
  - name: principal_currency
  - name: coupon_currency
  - name: rate_type
  - name: rate_sub_type
  - name: call_type
  - name: original_par_value
  - name: reopened_par_value
  - name: outstanding_par_value
  - name: issue_price
  - name: initial_coupon
  - name: min_denomination
  - name: multiples
  - name: day_count
  - name: pay_agent
  - name: variable_principal_ind
  - name: formula
- name: stg_call
  columns:
  - name: effective_date
  - name: cusip
  - name: call_type
  - name: start_date
  - name: end_date
  - name: next_call_date
  - name: date
  - name: call_freq
  - name: simp_index
  - name: formula
- name: stg_cpn
  columns:
  - name: effective_date
  - name: cusip
  - name: sequence
  - name: start_date
  - name: coupon
  - name: margin
  - name: simp_index
  - name: first_reset_date
  - name: coupon_freq
  - name: formula
- name: stg_dealer
  columns:
  - name: effective_date
  - name: cusip
  - name: dealer
- name: stg_ndx
  columns:
  - name: effective_date
  - name: cusip
  - name: sequence
  - name: description
  - name: reset_freq
  - name: usage

sources:
- name: fhlbof
  database: dbtdata
  schema: fhlbof
  tables:
  - name: bond
    description: Descriptive information about FHLB Domestic Bond, MTN and Global Issues
    columns:
    - name: CUSIP
    - name: SERIES
    - name: TRADED
    - name: ISSUED
    - name: MATURITY
    - name: TYPE
    - name: FIRSTCPN
    - name: F
    - name: PCR
    - name: CCR
    - name: R
    - name: S
    - name: CALL
    - name: ORIGINAL
    - name: REOPENED
    - name: OUTSTANDING
    - name: PRICE
    - name: COUPON
    - name: MINDENOM
    - name: MULTIPLES
    - name: DAYCNT
    - name: PAGENT
    - name: V
    - name: FORMULA
  - name: call
    description: Call structure information about FHLB Domestic Bond, MTN and Global Issues
    columns:
    - name: CUSIP
    - name: CALLTYPE
    - name: STARTDT
    - name: ENDDT
    - name: NEXTCALL
    - name: DATE
    - name: F
    - name: SIMPNDX
    - name: FORMULA
  - name: cpn
    description: Coupon information for bond, MTNs and Global Issues
    columns:
    - name: CUSIP
    - name: SEQ
    - name: START
    - name: COUPON
    - name: MARGIN
    - name: SIMPNDX
    - name: FIRSTRST
    - name: CPNFRQ
    - name: FORMULA
  - name: dlr
    description: Dealer information for bonds, MTNs and Global Issues
    columns:
    - name: CUSIP
    - name: DEALER
  - name: ndx
    description: Market index information for bond, MTNs and Global Issues
    columns:
    - name: CUSIP
    - name: SEQ
    - name: DESCRIP
    - name: COUPON
    - name: F
    - name: FIRSTRST
    - name: USAGE